
services:
    Happyr\Auth0Bundle\Factory\ManagementFactory:
        arguments:
            - '@Auth0\SDK\API\Authentication'
            - '%auth0.domain%' #domain
            - '@?auth0.cache'
            - ~ #http client
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: happyr_auth0 }

    Auth0\SDK\API\Management:
        factory: ['@Happyr\Auth0Bundle\Factory\ManagementFactory', 'create']
        lazy: true

    Auth0\SDK\API\Authentication:
        arguments:
            - 'https://%auth0.domain%'
            - '%auth0.client_id%'
            - '%auth0.client_secret%'
            - '%auth0.audience%'
            - '%auth0.scope%'
            - ~ # http client

    Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator:
        autowire: true
        autoconfigure: true

    Happyr\Auth0Bundle\Security\Auth0EntryPoint:
        arguments:
        - '@security.csrf.token_manager'
        - '@Symfony\Component\Security\Http\HttpUtils'
        - '%auth0.client_id%'
        - '%auth0.login_domain%'
        - '%auth0.scope%'
        - ~ # check path
