
services:
    happyr.auth0.api.authentication:
        class: Auth0\SDK\API\Authentication
        arguments:
            - "https://%auth0.domain%"
            - "%auth0.client_id%"
            - "%auth0.client_secret%"

    happyr.auth0.api.management.factory:
        class: Happyr\Auth0Bundle\Factory\ManagementFactory
        arguments:
            - "@auth0.cache"
            - "@happyr.auth0.api.authentication"
            - "%auth0.domain%"
            - "@?logger"

    happyr.auth0.api.management:
        class: Auth0\SDK\API\Management
        factory: ["@happyr.auth0.api.management.factory", "create"]
        lazy: true

    happyr.auth0.security.authentication.provider.sso:
        class: Happyr\Auth0Bundle\Security\Authentication\Provider\SSOProvider
        arguments: [~, '@happyr.auth0.api.authentication']
        public: false

    happyr.auth0.security.authentication.listener.sso:
        class: Happyr\Auth0Bundle\Security\Firewall\SSOListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
          - [ 'setAuthenticationApi', ["@happyr.auth0.api.authentication"]]

    happyr.auth0.security.authentication.entry_point.oauth:
        class: Happyr\Auth0Bundle\Security\EntryPoint\SSOEntryPoint
        arguments: [ "@security.http_utils", "%auth0.client_id%", "%auth0.domain%"]
        abstract: true
