services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Auth0\SDK\Configuration\SdkConfiguration:
        shared: false

    Auth0\SDK\Auth0:
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Auth0\SDK\API\Management:
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Auth0\SDK\API\Authentication:
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator: ~
    auth0.authenticator: '@Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator'

    Happyr\Auth0Bundle\Security\Auth0EntryPoint: ~
    auth0.entry_point: '@Happyr\Auth0Bundle\Security\Auth0EntryPoint'
