services:
    Happyr\Auth0Bundle\Factory\ConfigurationProvider:
        arguments:
            -
                clientId: '%auth0.client_id%'
                clientSecret: '%auth0.client_secret%'
                domain: '%auth0.domain%'
                scope: '%auth0.scope%'
                audience: '%auth0.audience%'
                httpRequestFactory: '@?Psr\Http\Message\RequestFactoryInterface'
                httpResponseFactory: '@?Psr\Http\Message\ResponseFactoryInterface'
                httpStreamFactory: '@?Psr\Http\Message\StreamFactoryInterface'
            - ~ # cache
            - ~ # http client

    Happyr\Auth0Bundle\Factory\Auth0Factory:
        arguments: ['@Happyr\Auth0Bundle\Factory\ConfigurationProvider']

    Auth0\SDK\Auth0:
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'auth0']
        lazy: true

    Auth0\SDK\API\Management:
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'management']
        lazy: true

    Auth0\SDK\API\Authentication:
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'authentication']
        lazy: true

    Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator:
        autowire: true
        autoconfigure: true

    Happyr\Auth0Bundle\Security\Auth0EntryPoint:
        arguments:
        - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
        - '@Symfony\Component\Security\Http\HttpUtils'
        - '%auth0.client_id%'
        - '%auth0.login_domain%'
        - '%auth0.scope%'
        - ~ # callback route
