services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Auth0\SDK\Configuration\SdkConfiguration: ~

    Auth0\SDK\Auth0:
        lazy: true
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Auth0\SDK\API\Management:
        lazy: true
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Auth0\SDK\API\Authentication:
        lazy: true
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator: ~

    auth0.authenticator: '@Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator'

    Happyr\Auth0Bundle\Security\Auth0EntryPoint:
        arguments:
            $configuration: '@Auth0\SDK\Configuration\SdkConfiguration'
            $csrfTokenManager: '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
            $httpUtils: '@Symfony\Component\Security\Http\HttpUtils'

    auth0.entry_point: '@Happyr\Auth0Bundle\Security\Auth0EntryPoint'
