services:
    Auth0\SDK\Configuration\SdkConfiguration: ~

    Auth0\SDK\Auth0:
        lazy: true
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'auth0']

    Auth0\SDK\API\Management:
        lazy: true
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'management']

    Auth0\SDK\API\Authentication:
        lazy: true
        factory: ['@Happyr\Auth0Bundle\Factory\Auth0Factory', 'authentication']

    Happyr\Auth0Bundle\Factory\Auth0Factory:
        arguments:
            $sdkConfiguration: '@Auth0\SDK\Configuration\SdkConfiguration'

    Happyr\Auth0Bundle\Security\Authentication\Auth0Authenticator:
        autowire: true
        autoconfigure: true

    Happyr\Auth0Bundle\Security\Auth0EntryPoint:
        arguments:
        - '@Auth0\SDK\Configuration\SdkConfiguration'
        - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
        - '@Symfony\Component\Security\Http\HttpUtils'
        - ~ # callback route
