name: Tests
on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.4', '8.0']
        strategy: [ 'highest', 'lowest' ]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.1.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.strategy }}

      - name: Run tests
        run: ./vendor/bin/simple-phpunit
